### ISSUE TITLE
temp/perm redirect

### ISSUE THREAD

**Issue by Benny-** [wgenial/mimetypeicons#2]
**Reproducible steps:**
1.  Go to https://mimetypeicons-wgenial.rhcloud.com/application/pdf?size=scalable

**Expected behavior:**
Get a permanent redirect (301) to https://mimetypeicons-wgenial.rhcloud.com/mimetypes-icons/scalable/application-pdf.svg

**Actual behavior:**
Get a temporary redirect (302) to https://mimetypeicons-wgenial.rhcloud.com/mimetypes-icons/scalable/application-pdf.svg

This saves a RTT if the icon is already cached. The browser refuses to show the icon before and during the request in case of a 301; just to be sure the original URL does not suddenly points somewhere else.

A 302 tell the browser it will not suddenly point somewhere else, and so the browser may cache this entire response.

**Comment by giovanigenerali** [comment]
@Benny- fixed, thank you!
