### ISSUE TITLE
perm/temp redirect

### ISSUE THREAD

**Issue by Benny-** [wgenial/mimetypeicons#3]
**Reproducible steps:**
1.  Go to https://mimetypeicons-wgenial.rhcloud.com/something.webp

**Expected behavior:**
Get a temporary redirect (302)

**Actual behavior:**
Get a permanent redirect (301)

Unknown types should not get a permanent redirect to the default icon. And this can be considered true too if a available size is missing, eg: request for https://peicons-wgenial.rhcloud.com/doc?size=4

Browsers might honor the 301 redirect forever. And it will be hard to convince them otherwise regardless if we finally have new icons for those new sweet mime-types. A solution would be to issue a 302 in case the direct might change in the future.

**Comment by giovanigenerali** [comment]
@Benny- fixed https://github.com/wgenial/mimetypeicons/commit/02b3324449098b9a3eeb754ebba6ef63a4fecc2e thank you!
